### ISSUE TITLE
Wrong link in Custom Resource Configuration in Openshift 4 Operator Hub

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi-operator#103]
The link in the documentation on Openshift 4 Operatorhub is dead.
```
Custom Resource Configuration

The bundled Custom Resource example represents the minimum settings needed to run the operator. If your environment needs more advanced settings (e.g. remote clusters, node mapping, etc.) please refer to the sample Custom Resource.
````

It forwards to
https://github.com/IBM/ibm-spectrum-scale-csi-operator/blob/1.0.0/stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml
which shows error 404(not found).

I think you missed the 'v' in the version (it should be v1.0.0) for your link.

**Comment by mew2057** [comment]
Adding to 1.0.1 Milestone, thought we caught this one.

**Comment by mew2057** [comment]
This should be cleared on the latest release on [OperatorHub](https://operatorhub.io/operator/ibm-spectrum-scale-csi-operator)
