### ISSUE TITLE
Two CSI operators on OperatorHub in Openshift 4

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi-operator#109]
When I search for CSI operator in OperatorHub panel in Openshift 4 dashboard, I can see two CSI operators. The official one and the second one marked as 'community edition'. The official edition still has the wrong link to custom resource configuration, the community edition has the correct link but I get a warning that this edition is not officially validated by Redhat. 

Please remove the redundant CSI operator from OperatoHub for Openshift 4. Also, make sure it is not marked as community edition.

**Comment by whowutwut** [comment]
Thanks for opening this, just responding to this comment: 

> Please remove the redundant CSI operator from OperatoHub for Openshift 4. Also, make sure it is not marked as community edition.

There are two versions, one that is certified by Redhat and one that is community for those running OKD or Kubernetes  (https://operatorhub.io/?keyword=ibm+spectrum)  Under Openshift, you should use the certified one.

**Comment by przem123** [comment]
Ok, but cant you just offer only the certified version? Dont think I need to have both of them in my Openshift dashboard.

**Comment by whowutwut** [comment]
The problem is that by doing what you suggest, we would have to delete the community one 
completely.  I think for now, we would want to offer both OpenShift and OKD/vanilla k8s users an option. 
 
Having it show up in your dashboard can be filtered out, on the left sidebar under OperatorHub,  you can check "Certified" and it will only show you certified plugins

![image](https://user-images.githubusercontent.com/10049070/71007529-24652800-20b5-11ea-8ad7-95fd5dc0cf0b.png)

Could this work for you?

**Comment by whowutwut** [comment]
So there's still some issues not addressed.... 

> The official edition still has the wrong link to custom resource configuration

Have to look into this one ☝️ 

> the community edition has the correct link but I get a warning that this edition is not officially validated by Redhat.

This is working as designed,  by OpenShift, for the community edition ones there's a disclaimer that comes up. These plugins are the ones you would find by going to operatorhub.io

**Comment by mew2057** [comment]
Yeah this particular issue is actually common to most operators, it's an artifact of the fact that we need to be available on vanilla k8s and openshift, this is more of an operatorhub issue than anything else.
