### ISSUE TITLE
Implement node mapping and node selector

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi-operator#13]
The operator API needs to expose the node mapping and node selector as defined in the template file from the [IBM Spectrum Scale CSI Driver](https://github.com/IBM/ibm-spectrum-scale-csi-driver/blob/master/deploy/spectrum-scale-config.json_template).

**Comment by mew2057** [comment]
This still needs a test case, my proposal:
1. Update CR with node mapping and node selector fields.
2. Verify pods have expected parameters.

**Comment by yadaven** [comment]
I tried testing with below manifest and worked fine with dev branch

piVersion: scale.ibm.com/v1alpha1
kind: 'CSIScaleOperator'
metadata:
# IMPORTANT THE OPERATOR LOOKS FOR THIS!
name: 'csi-scale-operator'
namespace: 'ibm-spectrum-scale-csi-driver'
status: {}
spec:

scaleHostpath: "/ibm/rgpfs2"
attacherNodeSelector:
- key: "scale"
value: "true"
- key: "infranode"
value: "2"

provisionerNodeSelector:
- key: "scale"
value: "true"
- key: "infranode"
value: "1"

pluginNodeSelector:

key: "scale"
value: "true"
nodeMapping:
- k8sNode: "vmip148"
spectrumscaleNode: "vmip148.gpfs.net"

clusters:
- id: "11953971138362021497"
secrets: "secret2"
secureSslMode: false
primary:
primaryFS: "rgpfs2"
primaryFset: "csiFset-vmip146-y2"
remoteCluster: "6788346196878642581"
remoteFs: "gpfs2"
restApi:
- guiHost: "192.168.9.149"
- id: "6788346196878642581"
secrets: "secret1"
secureSslMode: false
restApi:
- guiHost: "192.168.80.144"

**Comment by mew2057** [comment]
Closing, test case merged.
