### ISSUE TITLE
Missing options for remote cluster and remote filesystem

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi-operator#80]
How to set up a remote cluster with remote filesystem? This is missing in the readme. Also, in the sample secret file you dont show how it should look like. Can you describe it and provide an example with remote cluster and remote filesystem?

**Comment by mew2057** [comment]
@yadaven, I think you have  some  examples for this?

**Comment by mew2057** [comment]
It looks like PR  #78 should be addressing this issue.

**Comment by yadaven** [comment]
Yes in PR 78 we have provided example for RemoteFs and remote cluster

**Comment by przem123** [comment]
Can you provide a full sample yaml file with remote cluster, remote filesystem and remote GUI credentials included ? This would be very helpful.

Also, I dont see where I should include user credentials for csi user. I had to do that for the csi driver, but not sure how the operator gets it. Is it via a secret ? If yes, how should it look like ?
